spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: 192.168.120.130:9200
  thymeleaf:
    cache: false
server:
  port: 12000